import { Router } from 'express';
import authRoutes from './auth.routes';
import outletRoutes from './outlet.routes';
import menuRoutes from './menu.routes';
import orderRoutes from './order.routes';
import paymentRoutes from './payment.routes';
import customerRoutes from './customer.routes';
import tableRoutes from './table.routes';
import userRoutes from './user.routes';
import inventoryRoutes from './inventory.routes';
import recipeRoutes from './recipe.routes';
import supplierRoutes from './supplier.routes';
import purchaseRoutes from './purchase.routes';
import wastageRoutes from './wastage.routes';
import kitchenRoutes from './kitchen.routes';
import inventoryDashboardRoutes from './inventoryDashboard.routes';
import auditRoutes from './audit.routes';
import couponRoutes from './coupon.routes';
import loyaltyRoutes from './loyalty.routes';
import partyOrderRoutes from './partyOrder.routes';
import deliveryRoutes from './delivery.routes';
import notificationRoutes from './notification.routes';
import analyticsRoutes from './analytics.routes';
import dashboardRoutes from './dashboard.routes';
import searchRoutes from './search.routes';
import exportRoutes from './export.routes';
import printRoutes from './print.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/outlets', outletRoutes);
router.use('/menu', menuRoutes);
router.use('/orders', orderRoutes);
router.use('/payments', paymentRoutes);
router.use('/customers', customerRoutes);
router.use('/tables', tableRoutes);
router.use('/users', userRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/recipes', recipeRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/purchases', purchaseRoutes);
router.use('/wastage', wastageRoutes);
router.use('/kitchen', kitchenRoutes);
router.use('/inventory-dashboard', inventoryDashboardRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/coupons', couponRoutes);
router.use('/loyalty', loyaltyRoutes);
router.use('/party-orders', partyOrderRoutes);
router.use('/delivery', deliveryRoutes);
router.use('/notifications', notificationRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/search', searchRoutes);
router.use('/exports', exportRoutes);
router.use('/print', printRoutes);

export default router;
